# Generated by Django 4.2.5 on 2023-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='note_hash',
            field=models.TextField(null=True),
        ),
    ]
