# Generated by Django 4.2.5 on 2023-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_note_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Анонимные записки', 'verbose_name_plural': 'Анонимные записки'},
        ),
        migrations.AddField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
